stages:
  - test
  - build
  - docker
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

.gradle-cache: &gradle-cache
  cache:
    key: "gradle-$CI_RUNNER_OS-${CI_COMMIT_REF_SLUG}"
    paths:
      - .gradle/caches
      - .gradle/wrapper

unit-tests:
  stage: test
  image: eclipse-temurin:17-jdk
  <<: *gradle-cache
  script:
    - ./gradlew mergeTestReports --continue
  artifacts:
    when: always
    name: test-results
    paths:
      - build/test-results/combined/TEST-combined.xml
    reports:
      junit: build/test-results/combined/TEST-combined.xml
  allow_failure: true

build-jar:
  stage: build
  script:
    - echo "hello world"

docker-build:
  stage: docker
  script:
    - echo "hello world"

deploy:
  stage: deploy
  script:
    - echo "hello world"
